services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: secured-docs
    volumes:
      - postgres:/data/postgresql
      - ./schema.sql:/docker-entrypoint-initdb.dl/schema.sql
    ports:
      - 5431:5432
    networks:
      - spring-demo

  mail-dev:
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local