spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
      close-closeable: true
      flush-after-write-value: true
      write-date-keys-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

springdoc:
  default-consumes-media-type: application/json
application:
  mail:
      email-address: kayange@gmail.com
  security:
    jwt:
      secret-key: 404E635266556A586E32723538782F413F4428472B4B6250645367566B5970
      expiration: 86400000

server:
  servlet:
    context-path: /api/v1/